version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_code:cached
    ports:
      - "8000:8000"
